#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Quizard.Resource", IsApplication=true)]

namespace Quizard
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cardIconSmall = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int EditTextStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int quizIcon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int cardDialogAnswerButton = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int cardDialogExitButton = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int cardDialogTextView = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int cardTabListView = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int cardTabPlayButton = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int cardTabToolbar = 2131034119;
			
			// aapt resource value: 0x7f050017
			public const int createAnAccountButtonID = 2131034135;
			
			// aapt resource value: 0x7f050003
			public const int createNewAccountButtonID = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int editCardsButton = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int fragmentContainer = 2131034123;
			
			// aapt resource value: 0x7f050016
			public const int loginButtonID = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int loginProgressBarID = 2131034136;
			
			// aapt resource value: 0x7f050012
			public const int loginViewLinearLayoutID = 2131034130;
			
			// aapt resource value: 0x7f050002
			public const int newUserConfirmPasswordEditTextID = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int newUserPasswordEditTextID = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int newUserUsernameEditTextID = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int quizDialobNextButton = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int quizDialogRedoButton = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int quizRightWrongTextView = 2131034124;
			
			// aapt resource value: 0x7f050011
			public const int quizTabAnswerListView = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int quizTabQuestionTextView = 2131034128;
			
			// aapt resource value: 0x7f050015
			public const int rememberMeCheckBoxID = 2131034133;
			
			// aapt resource value: 0x7f05000d
			public const int toolbar1 = 2131034125;
			
			// aapt resource value: 0x7f050014
			public const int userLoginPasswordEditTextID = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int userLoginUsernameEditTextID = 2131034131;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreateAnAccountDialogLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DeckCardDialogBox = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DeckCardTab = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DeckLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DeckQuizDialogBox = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DeckQuizTab = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int LoginLayout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
