#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Quizard.Resource", IsApplication=true)]

namespace Quizard
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f090000
			public const int menuItems = 2131296256;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010006
			public const int layoutManager = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int reverseLayout = 2130771976;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int spanCount = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int stackFromEnd = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060008
			public const int common_action_bar_splitter = 2131099656;
			
			// aapt resource value: 0x7f060011
			public const int common_google_signin_btn_text_dark = 2131099665;
			
			// aapt resource value: 0x7f060009
			public const int common_google_signin_btn_text_dark_default = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_signin_btn_text_dark_disabled = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_signin_btn_text_dark_focused = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_signin_btn_text_dark_pressed = 2131099658;
			
			// aapt resource value: 0x7f060012
			public const int common_google_signin_btn_text_light = 2131099666;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_signin_btn_text_light_default = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_signin_btn_text_light_disabled = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int common_google_signin_btn_text_light_focused = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_signin_btn_text_light_pressed = 2131099662;
			
			// aapt resource value: 0x7f060013
			public const int common_plus_signin_btn_text_dark = 2131099667;
			
			// aapt resource value: 0x7f060000
			public const int common_plus_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_plus_signin_btn_text_dark_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_plus_signin_btn_text_dark_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_plus_signin_btn_text_dark_pressed = 2131099649;
			
			// aapt resource value: 0x7f060014
			public const int common_plus_signin_btn_text_light = 2131099668;
			
			// aapt resource value: 0x7f060004
			public const int common_plus_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_plus_signin_btn_text_light_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_plus_signin_btn_text_light_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_plus_signin_btn_text_light_pressed = 2131099653;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int item_touch_helper_swipe_escape_max_velocity = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int item_touch_helper_swipe_escape_velocity = 2131165186;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Cancel = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cardIconSmall = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_full_open_on_phone = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_disabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_focused = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_dark_normal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_dark_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_disabled = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_light_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_icon_light_pressed = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_disabled = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_dark_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_dark_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_dark_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_disabled = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_light_focused = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_light_normal = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_text_light_pressed = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_ic_googleplayservices = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_plus_signin_btn_icon_dark = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_plus_signin_btn_icon_dark_focused = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_dark_normal = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_light = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_light_disabled = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_icon_light_focused = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_icon_light_normal = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_icon_light_pressed = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_text_dark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_text_dark_disabled = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_text_dark_focused = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_dark_normal = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_dark_pressed = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_light_disabled = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_plus_signin_btn_text_light_focused = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_plus_signin_btn_text_light_normal = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_plus_signin_btn_text_light_pressed = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Create = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Delete = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int Edit = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int EditTextStyle = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int flashcard = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int Home_Icon = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int HomeICON = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int homepageIcon_small = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int play_icon = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int plusIcon = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int QuizardLogo = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int quizIcon = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int Settings = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int StartIcon = 2130837562;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080017
			public const int CardDeleteButtonID = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int CardEditButtonID = 2131230742;
			
			// aapt resource value: 0x7f080013
			public const int DeckAddCardCancelButton = 2131230739;
			
			// aapt resource value: 0x7f080012
			public const int DeckAddCardSaveButton = 2131230738;
			
			// aapt resource value: 0x7f080045
			public const int DeleteFlashSetMenuButtonID = 2131230789;
			
			// aapt resource value: 0x7f080044
			public const int EditFlashSetMenuButtonID = 2131230788;
			
			// aapt resource value: 0x7f080043
			public const int EnterIntoFlashSetMenuButtonID = 2131230787;
			
			// aapt resource value: 0x7f080029
			public const int PlayInfoTextViewID = 2131230761;
			
			// aapt resource value: 0x7f080050
			public const int PlaySetFront_ViewAnswerButton = 2131230800;
			
			// aapt resource value: 0x7f08004d
			public const int PlaySetQuestionTextView = 2131230797;
			
			// aapt resource value: 0x7f080015
			public const int QuestionAnswerTextViewID = 2131230741;
			
			// aapt resource value: 0x7f08000f
			public const int QuestionEditText = 2131230735;
			
			// aapt resource value: 0x7f080030
			public const int QuizTabHomeButtonID = 2131230768;
			
			// aapt resource value: 0x7f08003f
			public const int addToFlashSetListButtonID = 2131230783;
			
			// aapt resource value: 0x7f080001
			public const int adjust_height = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int adjust_width = 2131230722;
			
			// aapt resource value: 0x7f080027
			public const int answerTextBox = 2131230759;
			
			// aapt resource value: 0x7f080026
			public const int answerTextView = 2131230758;
			
			// aapt resource value: 0x7f080007
			public const int auto = 2131230727;
			
			// aapt resource value: 0x7f080036
			public const int cancelImageButtonID = 2131230774;
			
			// aapt resource value: 0x7f080037
			public const int cancelTextViewID = 2131230775;
			
			// aapt resource value: 0x7f080018
			public const int cardDialogEditTextID = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int cardDialogTextViewID = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int cardFlipButtonID = 2131230746;
			
			// aapt resource value: 0x7f08001d
			public const int cardTabAddButton = 2131230749;
			
			// aapt resource value: 0x7f08001c
			public const int cardTabHomeButton = 2131230748;
			
			// aapt resource value: 0x7f080023
			public const int cardTabListView = 2131230755;
			
			// aapt resource value: 0x7f08001e
			public const int cardTabPlayButton = 2131230750;
			
			// aapt resource value: 0x7f08001b
			public const int cardTabToolbar = 2131230747;
			
			// aapt resource value: 0x7f080034
			public const int createAFlashSetImageButtonID = 2131230772;
			
			// aapt resource value: 0x7f080035
			public const int createAFlashSetTextViewID = 2131230773;
			
			// aapt resource value: 0x7f08004b
			public const int createAnAccountButtonID = 2131230795;
			
			// aapt resource value: 0x7f08000d
			public const int createNewAccountButtonID = 2131230733;
			
			// aapt resource value: 0x7f080008
			public const int dark = 2131230728;
			
			// aapt resource value: 0x7f080020
			public const int deckAddCardAnswerEditTextID = 2131230752;
			
			// aapt resource value: 0x7f08001f
			public const int deckAddCardQuestionEditTextID = 2131230751;
			
			// aapt resource value: 0x7f080021
			public const int deckAddToDeckButtonID = 2131230753;
			
			// aapt resource value: 0x7f080022
			public const int deckDoneAddCardButtonID = 2131230754;
			
			// aapt resource value: 0x7f08002a
			public const int deckTextView = 2131230762;
			
			// aapt resource value: 0x7f08003a
			public const int deleteFlashSetImageButtonID = 2131230778;
			
			// aapt resource value: 0x7f08003b
			public const int deleteFlashSetTextViewID = 2131230779;
			
			// aapt resource value: 0x7f080038
			public const int editFlashSetSubjectImageButtonID = 2131230776;
			
			// aapt resource value: 0x7f080039
			public const int editFlashSetSubjectTextViewID = 2131230777;
			
			// aapt resource value: 0x7f080011
			public const int editText2 = 2131230737;
			
			// aapt resource value: 0x7f080042
			public const int enterIntoSelectedFlashSetButtonID = 2131230786;
			
			// aapt resource value: 0x7f080041
			public const int flashSetListViewID = 2131230785;
			
			// aapt resource value: 0x7f08003e
			public const int flashSetSubjectAutoCompleteTextViewID = 2131230782;
			
			// aapt resource value: 0x7f080028
			public const int fragmentContainer = 2131230760;
			
			// aapt resource value: 0x7f080004
			public const int icon_only = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int item_touch_helper_previous_elevation = 2131230720;
			
			// aapt resource value: 0x7f080009
			public const int light = 2131230729;
			
			// aapt resource value: 0x7f08004a
			public const int loginButtonID = 2131230794;
			
			// aapt resource value: 0x7f08004c
			public const int loginProgressBarID = 2131230796;
			
			// aapt resource value: 0x7f080046
			public const int loginViewLinearLayoutID = 2131230790;
			
			// aapt resource value: 0x7f080053
			public const int menuDeleteFlashSetId = 2131230803;
			
			// aapt resource value: 0x7f080052
			public const int menuEditFlashSetId = 2131230802;
			
			// aapt resource value: 0x7f080051
			public const int menuEnterFlashSetId = 2131230801;
			
			// aapt resource value: 0x7f08000c
			public const int newUserConfirmPasswordEditTextID = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int newUserPasswordEditTextID = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int newUserUsernameEditTextID = 2131230730;
			
			// aapt resource value: 0x7f08002b
			public const int nextCardButton = 2131230763;
			
			// aapt resource value: 0x7f080003
			public const int none = 2131230723;
			
			// aapt resource value: 0x7f08004f
			public const int playSetNoButton = 2131230799;
			
			// aapt resource value: 0x7f08004e
			public const int playSetYesButton = 2131230798;
			
			// aapt resource value: 0x7f080025
			public const int questionTextBox = 2131230757;
			
			// aapt resource value: 0x7f080024
			public const int questionTextView = 2131230756;
			
			// aapt resource value: 0x7f08002f
			public const int quizDialobNextButton = 2131230767;
			
			// aapt resource value: 0x7f08002e
			public const int quizDialogRedoButton = 2131230766;
			
			// aapt resource value: 0x7f08002d
			public const int quizRightWrongTextView = 2131230765;
			
			// aapt resource value: 0x7f080032
			public const int quizTabAnswerListView = 2131230770;
			
			// aapt resource value: 0x7f080033
			public const int quizTabNextButtonID = 2131230771;
			
			// aapt resource value: 0x7f080031
			public const int quizTabQuestionTextView = 2131230769;
			
			// aapt resource value: 0x7f080049
			public const int rememberMeCheckBoxID = 2131230793;
			
			// aapt resource value: 0x7f080040
			public const int searchFlashSetsSearchViewID = 2131230784;
			
			// aapt resource value: 0x7f08003c
			public const int settingsImageButtonID = 2131230780;
			
			// aapt resource value: 0x7f08003d
			public const int settingsTextViewID = 2131230781;
			
			// aapt resource value: 0x7f080005
			public const int standard = 2131230725;
			
			// aapt resource value: 0x7f08000e
			public const int textView1 = 2131230734;
			
			// aapt resource value: 0x7f080010
			public const int textView2 = 2131230736;
			
			// aapt resource value: 0x7f080014
			public const int toolbar1 = 2131230740;
			
			// aapt resource value: 0x7f080048
			public const int userLoginPasswordEditTextID = 2131230792;
			
			// aapt resource value: 0x7f080047
			public const int userLoginUsernameEditTextID = 2131230791;
			
			// aapt resource value: 0x7f08002c
			public const int viewAnswerButton = 2131230764;
			
			// aapt resource value: 0x7f080006
			public const int wide = 2131230726;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreateAnAccountDialogLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DeckAddCardLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DeckCardDialogBox = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DeckCardTab = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DeckCardTabEditLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DeckLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int deckPlayLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int DeckQuizDialogBox = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int DeckQuizTab = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int HomeLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int HomeMenuDialogLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int LoginLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int PlaySetLayout_Back = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int PlaySetLayout_Front = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int menuItems = 2131427328;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04001f
			public const int ApplicationName = 2130968607;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_api_unavailable_text = 2130968600;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_enable_button = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_enable_text = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_enable_title = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_button = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_install_text_phone = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_install_text_tablet = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int common_google_play_services_install_title = 2130968580;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_invalid_account_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_invalid_account_title = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int common_google_play_services_network_error_text = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_network_error_title = 2130968592;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_notification_ticker = 2130968579;
			
			// aapt resource value: 0x7f04001c
			public const int common_google_play_services_restricted_profile_text = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_restricted_profile_title = 2130968603;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_sign_in_failed_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_sign_in_failed_title = 2130968601;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_unknown_issue = 2130968578;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_unsupported_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_unsupported_title = 2130968596;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_update_button = 2130968598;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_update_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_update_title = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_play_services_updating_text = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_updating_title = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_wear_update_text = 2130968589;
			
			// aapt resource value: 0x7f040017
			public const int common_open_on_phone = 2130968599;
			
			// aapt resource value: 0x7f04001d
			public const int common_signin_button_text = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int common_signin_button_text_long = 2130968606;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int CustomActionToolbarTheme = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int HomeActionBar = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int ListViewStyle_Light = 2131361794;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
